language: node_js
node_js:
  - "iojs"
  - "7"
cache:
  yarn: true
  directories:
    - elm-stuff
    - node_modules
env:
  global:
    - YARN_VERSION=1.7.0
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  - export PATH="$HOME/.yarn/bin:$PATH"
install: 
  - yarn
  - yarn prod